Let's import the Pandas library

In [38]:
import pandas as pd

Let's create an empty Pandas Series

In [39]:
empty_series = pd.Series()
empty_series

Series([], dtype: object)

In [40]:
type(empty_series)

pandas.core.series.Series

In [41]:
empty_series.dtype

dtype('O')

In [42]:
empty_series.ndim

1

In [43]:
empty_series.shape

(0,)

In [44]:
empty_series.size

0

In [45]:
empty_series.index  # get index of Series as a RangeIndex object

RangeIndex(start=0, stop=0, step=1)

In [46]:
empty_series.values  # get values stored in Series as a NumPy array

array([], dtype=object)

In [47]:
# The default name of a series is None, the '0' you see at the top of the series is just a visual artifact which cannot be accessed
empty_series.name

In [48]:
type(empty_series.name)

NoneType

Let's create a Series with elements

In [49]:
my_series = pd.Series(data = [1, 2, 3, 4])
my_series

0    1
1    2
2    3
3    4
dtype: int64

In [50]:
type(my_series)

pandas.core.series.Series

In [51]:
my_series.dtype

dtype('int64')

In [52]:
my_series.ndim

1

In [53]:
my_series.shape

(4,)

In [54]:
my_series.size

4

In [55]:
my_series.index

RangeIndex(start=0, stop=4, step=1)

In [56]:
my_series.values

array([1, 2, 3, 4])

In [57]:
mixed_series = pd.Series([1, True, 'yes', 3.14, [42, 0]])
mixed_series

0          1
1       True
2        yes
3       3.14
4    [42, 0]
dtype: object

In [58]:
mixed_series.dtype

dtype('O')

We can create a Series with a custom index and name

In [59]:
named_series = pd.Series(data = ['Ashok', 'Kumar', 18, 183], index = ['Forename', 'Surname', 'Age', 'Height'], name = 'Student Info')
named_series

Forename    Ashok
Surname     Kumar
Age            18
Height        183
Name: Student Info, dtype: object

In [60]:
named_series['Forename']

'Ashok'

In [61]:
named_series.dtype

dtype('O')

In [62]:
named_series.ndim

1

In [63]:
named_series.shape

(4,)

In [64]:
named_series.size

4

In [65]:
named_series.index

Index(['Forename', 'Surname', 'Age', 'Height'], dtype='object')

In [66]:
named_series.values

array(['Ashok', 'Kumar', 18, 183], dtype=object)

In [67]:
named_series.name

'Student Info'

In [68]:
# pd.Series(data = [1, 2, 3], index = ['A', 'B', 'C', 'D'])  # the length of the data and index should match

We can create Series from other data structures

In [69]:
my_list = [1, 2, 3, 4]
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [70]:
my_tuple = (1, 2, 3, 4)
pd.Series(my_tuple)

0    1
1    2
2    3
3    4
dtype: int64

In [71]:
# my_set = {1, 2, 3, 4}
# pd.Series(my_set)  # sets are unordered and cannot be used to make a Series

In [72]:
my_dict = {'A': 1, 'B': 2, 'C': 3, 'D': 4}
pd.Series(my_dict)

A    1
B    2
C    3
D    4
dtype: int64

Pandas Series are strictly one dimensional

In [73]:
pd.Series([[1, 2], [3, 4], [5, 6]])

0    [1, 2]
1    [3, 4]
2    [5, 6]
dtype: object

In [74]:
# import numpy as np
# pd.Series(np.array([[1, 2], [3, 4], [5, 6]]))