Let's import the Pandas library

In [30]:
!python --version

Python 3.10.12

In [31]:
import pandas as pd

In [32]:
my_series = pd.Series(data = [32, 33, 30, 29, 36], index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], name = 'Peak Temperature')
my_series

Mon    32
Tue    33
Wed    30
Thu    29
Fri    36
Name: Peak Temperature, dtype: int64

In [33]:
# my_series[0]  # will throw a FutureWarning

We can index and slice Series by position with `.iloc[]`, the integer-location-based (position-based) indexer

In [34]:
my_series.iloc[0]

32

In [35]:
my_series.iloc[4]

36

In [36]:
my_series.iloc[-1]

36

In [37]:
my_series.iloc[1:3]  # .iloc[] excludes the last element, much like regular indexing

Tue    33
Wed    30
Name: Peak Temperature, dtype: int64

In [38]:
my_series.iloc[::-1]

Fri    36
Thu    29
Wed    30
Tue    33
Mon    32
Name: Peak Temperature, dtype: int64

We can also index and slice Series using `.loc[]`, the label-based indexer, or just by using regular subscripting

In [39]:
my_series['Tue']

33

In [40]:
my_series.loc['Tue']

33

In [41]:
my_series.loc['Tue':]

Tue    33
Wed    30
Thu    29
Fri    36
Name: Peak Temperature, dtype: int64

In [42]:
my_series.loc['Tue':'Thu']  # .loc[] is inclusive of the last element, unlike .iloc[]

Tue    33
Wed    30
Thu    29
Name: Peak Temperature, dtype: int64

In [43]:
my_series.loc['Tue':'Thu':2]

Tue    33
Thu    29
Name: Peak Temperature, dtype: int64

If we sort the series, observe how `.iloc[]` reflects the new positions whereas `.loc[]` follows the same labels as before

In [44]:
my_series

Mon    32
Tue    33
Wed    30
Thu    29
Fri    36
Name: Peak Temperature, dtype: int64

In [45]:
sorted_series = my_series.sort_values()  # method to sort by values in ascending order
sorted_series

Thu    29
Wed    30
Mon    32
Tue    33
Fri    36
Name: Peak Temperature, dtype: int64

In [46]:
my_series.iloc[1]

33

In [47]:
sorted_series.iloc[1]

30

In [48]:
my_series.loc['Tue']

33

In [49]:
sorted_series.loc['Tue']

33

We can indexing Series with conditions

In [50]:
mask = my_series >= 30  # creating a 'boolean mask' which we can use to index the series
mask

Mon     True
Tue     True
Wed     True
Thu    False
Fri     True
Name: Peak Temperature, dtype: bool

In [51]:
my_series.loc[mask]

Mon    32
Tue    33
Wed    30
Fri    36
Name: Peak Temperature, dtype: int64

In [52]:
my_series.loc[my_series.isin([28, 29, 30])]  # checks if value belongs to the list

Wed    30
Thu    29
Name: Peak Temperature, dtype: int64

In [53]:
my_series.loc[~my_series.isin([28, 29, 30])]  # negation of the above; checks if value does not belong to the list

Mon    32
Tue    33
Fri    36
Name: Peak Temperature, dtype: int64

In [54]:
# my_series.loc[(my_series >= 30) and (my_series < 35)]  # in Pandas, while chaining conditions, use ~ for not; | for or; & for and

In [55]:
my_series.loc[(my_series >= 30) & (my_series < 35)]

Mon    32
Tue    33
Wed    30
Name: Peak Temperature, dtype: int64

We can use 'fancy indexing' to retrieve only certain elements of a Series by its positional or label-based index

In [56]:
my_series.iloc[[0, 0, 4, 2]]

Mon    32
Mon    32
Fri    36
Wed    30
Name: Peak Temperature, dtype: int64

In [57]:
my_series.loc[['Mon', 'Wed', 'Fri', 'Fri']]

Mon    32
Wed    30
Fri    36
Fri    36
Name: Peak Temperature, dtype: int64